spring.application.name=NotifApp

# Amazon MQ - ActiveMQ (MQTT over SSL)
mqtt.broker-url=mqtt+ssl://b-98d2224e-151d-45e1-9f1b-634e363140a3-1.mq.ap-southeast-1.amazonaws.com:8883
mqtt.username=notifuser
mqtt.password=Adminpass@123
mqtt.client-id=spring-producer
mqtt.topic=recharge/notifications

server.port=8080
