spring.application.name=NotifApp

# Amazon MQ - ActiveMQ (MQTT over SSL)
mqtt.broker-url=ssl://b-62ddd103-66d2-4944-a7d2-0e8f8463a4a3-1.mq.ap-south-1.amazonaws.com:61617
mqtt.username=notifuser
mqtt.password=Adminpass@123
mqtt.client-id=spring-producer
mqtt.topic=recharge/notifications

server.port=8080
